name: ➕ New Provider
description: Submit details for a new network provider. 
title: "[NEWPROVIDER] - <name>"
labels: ["provider"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out the form!

  - type: input
    id: name
    attributes:
      label: "Provider Name"
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: "Provider URL"
    validations:
      required: true

  - type: input
    id: asn
    attributes:
      label: "Provider ASN"
    validations:
      required: true

  - type: checkboxes
    id: bgpCommunities
    attributes:
      label: BGP Communities
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true

  - type: input
    id: bgpCommunitiesUrl
    attributes:
      label: "Link to BGP communities (if available)"

  - type: checkboxes
    id: bgpPassThrough
    attributes:
      label: BGP Communities Pass-through
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true

  - type: checkboxes
    id: autoFilters
    attributes:
      label: Automatic IRR filters
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true

  - type: checkboxes
    id: rpkiFilter
    attributes:
      label: RPKI Filter
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true

  - type: checkboxes
    id: loaRequired
    attributes:
      label: LOA Required
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true

  - type: checkboxes
    id: ipv6Support
    attributes:
      label: IPv6 Support
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true

  - type: dropdown
    id: table
    attributes:
      label: What type of BGP table can you provide?
      options:
        - "Full Table + Default"
        - "Partial Table + Default"
        - "Default"
        - "No Table"
    validations:
      required: true

  - type: textarea
    id: locations
    attributes:
      label: Locations
      placeholder: Enter locations here
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: checkboxes
    id: downstreamSupport
    attributes:
      label: Downstream Support (AS-SET)
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true

  - type: checkboxes
    id: policyAgreement
    attributes:
      label: Policy
      description: By submitting this issue, you have read the policy and the provider falls within the [Policy](https://https://bgp.cheap/policy) to be added
      options:
        - label: "I agree that the provider falls within this policy"
    validations:
      required: true
